version = 0.1

[default.deploy.parameters]
stack_name = "wisewords"
resolve_s3 = true
s3_prefix = "wisewords"
region = "eu-west-2"
profile = "deploy-to-production-profile"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
